# Mods
mods = [
    "sodium",
    "iris",
    "lithium",
    "indium",
    "fabric-api",
]

# Resource packs
resourcepacks = [
    "faithful-32x",
    "fresh-animations",
]

# Shaders
shaders = [
    "complementary-reimagined",
    "bsl-shaders",
]